## Copyright (C) 2012 Abdulla Kamar. All rights reserved. ##

def build( context ):
    context.program(
        source = 'binary_test.cpp fixed_cache_test.cpp pointer_test.cpp',
        target = 'utility_test',
        use = 'unit' )
