Import( Split( 'name ooe platform root' ) )
build = root.Clone()
build.Append( LIBS = ooe.rt.library )

if name == 'darwin':
	build.Append( LINKFLAGS = '-Wl,-install_name,@executable_path/../library/libipc.dylib' )

files = Glob( '*.cpp' ) + Glob( 'memory/*.cpp' ) + Glob( 'socket/*.cpp' )
files += Glob( platform + '/foundation/ipc/socket/*.cpp' )
out = build.SharedLibrary( '#library/libipc', files )
build.SideEffect( Glob( '*.rpo' ), out )
