Import( Split( 'name platform root' ) )

### build ######################################################################
build = root.Clone()

if name == 'darwin':
	build.Append( LINKFLAGS = '-Wl,-install_name,@rpath/libipc.dylib' )

files = Glob( '*.cpp' ) + Glob( 'memory/*.cpp' ) + Glob( 'socket/*.cpp' )
files += Glob( platform + '/foundation/ipc/*.cpp' )
files += Glob( platform + '/foundation/ipc/memory/*.cpp' )
files += Glob( platform + '/foundation/ipc/socket/*.cpp' )
out = build.SharedLibrary( '#library/libipc', files )
build.SideEffect( Glob( '*.rpo' ), out )
