Import( Split( 'name ooe root' ) )
build = root.Clone()
build.Append( LIBS = ooe.rt.library )

if name == 'darwin':
	build.Append( LINKFLAGS = '-Wl,-install_name,@executable_path/library/libipc.dylib' )

files = Glob( '*.cpp' ) + Glob( 'memory/*.cpp' ) + Glob( 'socket/*.cpp' )
out = build.SharedLibrary( '#/build/library/libipc', files )
build.SideEffect( Glob( '*.rpo' ), out )
