## Copyright (C) 2010 Abdulla Kamar. All rights reserved. ##

def build( context ):
    platform = context.env.platform

    context.shlib(
        linkflags = platform.shlib( 'ipc' ),
        source = 'name.cpp nameservice.cpp pool.cpp semaphore.cpp shared_memory.cpp ' +
            'switchboard.cpp memory/client.cpp memory/link.cpp memory/server.cpp ' +
            'memory/transport.cpp socket/client.cpp socket/server.cpp ' + source( platform.name ),
        target = 'ipc',
        use = 'io parallel' )

def source( name ):
    if name == 'darwin':
        return 'memory/darwin/transport.cpp'
    elif name == 'linux':
        return 'memory/linux/transport.cpp'
