## Copyright (C) 2012 Abdulla Kamar. All rights reserved. ##

def build( context ):
    platform = context.env.platform

    context.shlib(
        linkflags = platform.shlib( 'ipc' ),
        source = 'name.cpp nameservice.cpp pool.cpp semaphore.cpp shared_memory.cpp ' +
            'switchboard.cpp memory/client.cpp memory/link.cpp memory/server.cpp ' +
            'memory/transport.cpp socket/client.cpp socket/server.cpp ' + source( platform.name ),
        target = 'ipc',
        use = 'io parallel' )

    context.program(
        source = 'shared_memory_test.cpp upgrade_test.cpp memory/rpc_test.cpp socket/rpc_test.cpp',
        target = 'ipc_test',
        use = 'ipc unit' )

def source( name ):
    if name == 'darwin':
        return 'memory/darwin/transport.cpp'
    elif name == 'linux':
        return 'memory/linux/transport.cpp'
