/* Copyright (C) 2010 Abdulla Kamar. All rights reserved. */

#ifndef OOE_FOUNDATION_EXECUTABLE_PROGRAM_FORWARD_HPP
#define OOE_FOUNDATION_EXECUTABLE_PROGRAM_FORWARD_HPP

#define OOE_SIGFAULT SIGSEGV

#endif	// OOE_FOUNDATION_EXECUTABLE_PROGRAM_FORWARD_HPP
