/* Copyright (C) 2010 Abdulla Kamar. All rights reserved. */

#ifndef OOE_PLATFORM_POSIX_FOUNDATION_IPC_ERROR_FORWARD_HPP
#define OOE_PLATFORM_POSIX_FOUNDATION_IPC_ERROR_FORWARD_HPP

#define OOE_NOEXIST ENOENT

#endif  // OOE_PLATFORM_POSIX_FOUNDATION_IPC_ERROR_FORWARD_HPP
