/* Copyright (C) 2010 Abdulla Kamar. All rights reserved. */

#ifndef OOE_FOUNDATION_IPC_ERROR_FORWARD_HPP
#define OOE_FOUNDATION_IPC_ERROR_FORWARD_HPP

#define OOE_NOEXIST ENOENT

#endif	// OOE_FOUNDATION_IPC_ERROR_FORWARD_HPP
