## Copyright (C) 2010 Abdulla Kamar. All rights reserved. ##

def build( context ):
    platform = context.env.platform

    context.program(
        source = 'inject.cpp main.cpp',
        target = 'mock',
        use = 'executable' )
