/* Copyright (C) 2012 Abdulla Kamar. All rights reserved. */

#ifndef OOE_FOUNDATION_IPC_LINUX_ERROR_FORWARD_HPP
#define OOE_FOUNDATION_IPC_LINUX_ERROR_FORWARD_HPP

#define OOE_NOEXIST ENOENT

#endif  // OOE_FOUNDATION_IPC_LINUX_ERROR_FORWARD_HPP
