Import( Split( 'name ooe platform root' ) )

### configure ##################################################################
build = root.Clone()

if not build.GetOption( 'clean' ):
	setup = Configure( build )

	if name == 'darwin':
		if not setup.CheckCHeader( 'OpenGL/OpenGL.h' ): Exit( 1 )
	elif name == 'posix':
		if not setup.CheckLibWithHeader( ooe.gl.library, 'GL/glx.h', 'c' ): Exit( 1 )

	build = setup.Finish()

### build ######################################################################
files = Glob( '*.cpp' ) + Glob( platform + '/foundation/opengl/*.cpp' )
files += Glob( platform + '/foundation/opengl/*.mm' )
out = build.SharedLibrary( '#library/libopengl', files )
build.SideEffect( Glob( '*.rpo' ), out )
