## Copyright (C) 2010 Abdulla Kamar. All rights reserved. ##

def build( context ):
    platform = context.env.platform
    context.shlib(
        framework = platform.opengl.framework,
        lib = platform.opengl.lib,
        source = 'block.cpp buffer.cpp device.cpp frame.cpp program.cpp shader.cpp symbol.cpp ' +
            'target.cpp texture.cpp ' + source( platform.name ),
        target = 'opengl',
        use = 'visual' )

def source( name ):
    if name == 'darwin':
        return 'darwin/context.mm'
    elif name == 'linux':
        return 'linux/context.cpp'
