## Copyright (C) 2012 Abdulla Kamar. All rights reserved. ##

def build( context ):
    platform = context.env.platform

    context.shlib(
        framework = platform.opengl.framework,
        lib = platform.opengl.lib,
        linkflags = platform.shlib( 'opengl' ),
        source = 'block.cpp buffer.cpp device.cpp frame.cpp program.cpp shader.cpp symbol.cpp ' +
            'target.cpp texture.cpp ' + source( platform.name ),
        target = 'opengl',
        use = 'visual' )

    context.program(
        source = 'frame_test.cpp texture_test.cpp',
        target = 'opengl_test',
        use = 'math unit visual' )

def source( name ):
    if name == 'darwin':
        return 'darwin/context.mm'
    elif name == 'linux':
        return 'linux/context.cpp'
