find_path( OPENEXR_INCLUDE_DIRS ImfIO.h PATH_SUFFIXES OpenEXR )
find_library( HALF_LIBRARY Half )
find_library( IEX_LIBRARY Iex )
find_library( ILMIMF_LIBRARY IlmImf )
find_library( ILMTHREAD_LIBRARY IlmThread )
set( OPENEXR_LIBRARIES ${HALF_LIBRARY} ${IEX_LIBRARY} ${ILMIMF_LIBRARY} ${ILMTHREAD_LIBRARY} )
mark_as_advanced( OPENEXR_LIBRARIES OPENEXR_INCLUDE_DIRS HALF_LIBRARY IEX_LIBRARY ILMIMF_LIBRARY
    ILMTHREAD_LIBRARY )

include( FindPackageHandleStandardArgs )
find_package_handle_standard_args( OpenEXR DEFAULT_MSG OPENEXR_LIBRARIES OPENEXR_INCLUDE_DIRS )
