## Copyright (C) 2010 Abdulla Kamar. All rights reserved. ##

def build( context ):
    platform = context.env.platform

    context.shlib(
        linkflags = platform.shlib( 'math' ),
        source = 'camera.cpp geometry.cpp math.cpp',
        target = 'math' )
