## Copyright (C) 2010 Abdulla Kamar. All rights reserved. ##

def build( context ):
    platform = context.env.platform

    context.shlib(
        lib = platform.python.lib,
        libpath = platform.python.libpath,
        linkflags = platform.shlib( 'python_link' ),
        source = 'facade.cpp vm.cpp',
        target = 'python_link',
        use = 'registry' )

    context.program(
        source = 'host/main.cpp',
        target = 'host/python_host',
        use = 'python_link' )
