## Copyright (C) 2010 Abdulla Kamar. All rights reserved. ##

def build( context ):
    platform = context.env.platform
    context.shlib(
        lib = platform.python.lib,
        libpath = platform.python.libpath,
        source = 'facade.cpp vm.cpp',
        target = 'python',
        use = 'registry' )
