/* Copyright (C) 2010 Abdulla Kamar. All rights reserved. */

#ifndef OOE_FOUNDATION_OPENGL_LINUX_SYMBOL_FORWARD_HPP
#define OOE_FOUNDATION_OPENGL_LINUX_SYMBOL_FORWARD_HPP

#define OOE_APPLE_SYMBOL

#endif  // OOE_FOUNDATION_OPENGL_LINUX_SYMBOL_FORWARD_HPP
