/* Copyright (C) 2010 Abdulla Kamar. All rights reserved. */

#ifndef OOE_FOUNDATION_OPENGL_DARWIN_SYMBOL_FORWARD_HPP
#define OOE_FOUNDATION_OPENGL_DARWIN_SYMBOL_FORWARD_HPP

#define OOE_APPLE_SYMBOL "APPLE"

#endif  // OOE_FOUNDATION_OPENGL_DARWIN_SYMBOL_FORWARD_HPP
