Import( Split( 'name root' ) )
build = root.Clone()

if name == 'darwin':
	build.Append( LINKFLAGS = '-Wl,-install_name,@executable_path/../library/libscene.dylib' )

out = build.SharedLibrary( '#library/libscene', Glob( '*.cpp' ) )
build.SideEffect( Glob( '*.rpo' ), out )
