## Copyright (C) 2010 Abdulla Kamar. All rights reserved. ##

def build( context ):
    platform = context.env.platform

    context.shlib(
        framework = platform.visual.framework,
        includes = platform.visual.includes,
        lib = 'freetype',
        linkflags = platform.shlib( 'visual' ),
        source = 'font.cpp graphics.cpp ' + source( platform.name ),
        target = 'visual',
        use = 'image' )

def source( name ):
    if name == 'darwin':
        return 'darwin/event_queue.mm darwin/sight.mm darwin/view.mm'
    elif name == 'linux':
        return 'linux/event_queue.cpp linux/sight.cpp linux/view.cpp'
