## Copyright (C) 2010 Abdulla Kamar. All rights reserved. ##

def build( context ):
    context.shlib(
        lib = 'v8',
        source = 'facade.cpp vm.cpp',
        target = 'javascript',
        use = 'registry' )
