Import( Split( 'name platform root' ) )

### configure ##################################################################
setup = Configure( root.Clone() )

if name == 'posix':
	if not setup.CheckFunc( 'splice', '#include <fcntl.h>' ): Exit( 1 )

build = setup.Finish()

### build ######################################################################
if name == 'darwin':
	build.Append( LINKFLAGS = '-Wl,-install_name,@executable_path/../library/libio.dylib' )

files = Glob( '*.cpp' ) + Glob( platform + '/foundation/io/*.cpp' )
out = build.SharedLibrary( '#library/libio', files )
build.SideEffect( Glob( '*.rpo' ), out )
