## Copyright (C) 2010 Abdulla Kamar. All rights reserved. ##

def build( context ):
    platform = context.env.platform

    context.shlib(
        framework = platform.executable.framework,
        linkflags = platform.shlib( 'executable' ),
        source = 'environment.cpp fork_io.cpp library.cpp program.cpp timer.cpp ' +
            source( platform.name ),
        target = 'executable' )

def source( name ):
    if name == 'darwin':
        return 'darwin/environment.cpp darwin/program.mm darwin/timer.cpp'
    elif name == 'linux':
        return 'linux/environment.cpp linux/program.cpp linux/timer.cpp'
