/* Copyright (C) 2010 Abdulla Kamar. All rights reserved. */

#ifndef OOE_PLATFORM_DARWIN_FOUNDATION_PARALLEL_THREAD_FORWARD_HPP
#define OOE_PLATFORM_DARWIN_FOUNDATION_PARALLEL_THREAD_FORWARD_HPP

#define OOE_TLS( type ) ooe::tls< type >

#endif  // OOE_PLATFORM_DARWIN_FOUNDATION_PARALLEL_THREAD_FORWARD_HPP
