/* Copyright (C) 2012 Abdulla Kamar. All rights reserved. */

#ifndef OOE_FOUNDATION_IPC_DARWIN_ERROR_FORWARD_HPP
#define OOE_FOUNDATION_IPC_DARWIN_ERROR_FORWARD_HPP

#define OOE_NOEXIST EINVAL

#endif  // OOE_FOUNDATION_IPC_DARWIN_ERROR_FORWARD_HPP
