Import( Split( 'name ooe root' ) )

### configure ##################################################################
build = root.Clone()
build.Append( CPPPATH = ooe.lua.include_path )
setup = Configure( build )

if not setup.CheckLibWithHeader( ooe.lua.library, 'lauxlib.h', 'c' ): Exit( 1 )

build = setup.Finish()

### build ######################################################################
if name == 'darwin':
	build.Append( LINKFLAGS = '-Wl,-install_name,@executable_path/library/liblua.dylib' )

out = build.SharedLibrary( '#/build/library/liblua', Glob( '*.cpp' ) )
build.SideEffect( Glob( '*.rpo' ), out )
