Import( Split( 'name ooe root' ) )

### configure ##################################################################
build = root.Clone()
build.Append( CPPPATH = ooe.lua.include_path )

if not build.GetOption( 'clean' ):
	setup = Configure( build )

	if not setup.CheckLibWithHeader( ooe.lua.library, 'lauxlib.h', 'c' ):
		Exit( 1 )

	build = setup.Finish()

### build ######################################################################
if name == 'darwin':
	build.Append( LINKFLAGS = '-Wl,-install_name,@rpath/liblua.dylib' )

out = build.SharedLibrary( '#library/liblua', Glob( '*.cpp' ) )
build.SideEffect( Glob( '*.rpo' ), out )
