#!/bin/sh

PLATFORM="$1"
shift 1

NAME=`echo "$@" | awk -F ' ' '{ printf $NF }'`
TYPE=`echo "$NAME" | cut -d . -f 2`

if [ "$TYPE" = 'mm' ]; then
	printf "    \033[46m[CC]\033[0m    $NAME\n"
	exec g++-4.2 $@
elif [ "$TYPE" = 'cpp' ]; then
	printf "    \033[42m[CC]\033[0m    $NAME\n"
else
	NAME=`echo "$@" | cut -d ' ' -f 2`
	printf "    \033[43m[LD]\033[0m    $NAME\n"
fi

if [ "$PLATFORM" = 'posix' ]; then
	exec g++ $@
elif [ "$PLATFORM" = 'darwin' ]; then
	exec g++-4 $@
else
	printf "Unknown platform: $PLATFORM\n"
	exit 1
fi
