#!/bin/sh

trap 'rm -f $FILE; kill -9 $LID $PID 2> /dev/null; echo; exit;' 1 2 3 6 9 14 15

BEGIN=`[ $# -ge 1 ] && echo $1 || echo 0`
END=`[ $# -ge 2 ] && echo $2 || echo 3`
FILE=`mktemp`

for X in `seq $BEGIN $END`; do
	printf ">>> method $X\n"

	for Y in `seq 0 10`; do
		I=50
		printf "$Y threads, $I iterations"

		LID=''

		for N in `seq $Y`; do
			binary/ipc_test -l 1 &
			LID="$LID $!"
		done

		binary/ipc_test -s $X &
		PID=$!
		sleep 1

		for Z in `seq $I`; do
			binary/ipc_test -c $X >> $FILE
			printf .
		done

		kill -9 $LID $PID
		VALUES=`cat $FILE | script/stddev`
		rm $FILE

		printf "done\n\tMean (stddev) μs/call: %f (%f)\n" $VALUES
	done

	printf '\n'
done
