#!/bin/bash

function clean()
{
	rm -f $FILE
	kill -9 $PID 2> /dev/null
	rm -f /tmp/result-*
	killall -9 ipc_test 2> /dev/null
	echo
	exit
}

trap clean 1 2 3 6 9 14 15

BEGIN=`[ $# -ge 1 ] && echo $1 || echo 0`
END=`[ $# -ge 2 ] && echo $2 || echo 3`
FILE=`mktemp`

# bash required for function syntax
function spawn()
{
	for I in `seq $2`; do
		./build/ipc_test -c $1 | bc -l > /tmp/result-$I &
		LIST="$LIST $!"
	done

	wait $LIST
	SUM=0

	for I in `seq $2`; do
		SUM="$SUM + `cat /tmp/result-$I`"
	done

	rm -f /tmp/result-*
	echo "( $SUM ) / $I"
}

for X in `seq $BEGIN $END`; do
	printf ">>> method $X\n"

	for Y in `seq 1 50`; do
		I=50
		printf "$Y processes, $I iterations"

		./build/ipc_test -s $X &
		PID=$!
		sleep 1

		for Z in `seq $I`; do
			spawn $X $Y 2> /dev/null | bc -l >> $FILE
			printf .
		done

		kill -9 $PID
		VALUES=`cat $FILE | ./script/stddev`
		rm $FILE

		printf "done\n\tMean (stddev) μs/call: %f (%f)\n" $VALUES
	done

	printf '\n'
done
