#!/usr/bin/env python

import sys

sum = 0.
sum_sq = 0.
n = 0

for line in sys.stdin:
	x = float( line )
	sum += x
	sum_sq += x ** 2
	n += 1

mean = sum / n
stddev = ( ( sum_sq / n ) - mean ** 2 ) ** 0.5
print mean, stddev
