/* Copyright (C) 2012 Abdulla Kamar. All rights reserved. */

#ifndef OOE_FOUNDATION_UTILITY_DARWIN_POINTER_FORWARD_HPP
#define OOE_FOUNDATION_UTILITY_DARWIN_POINTER_FORWARD_HPP

extern "C" void free( void* );

#endif  // OOE_FOUNDATION_UTILITY_DARWIN_POINTER_FORWARD_HPP
