## Copyright (C) 2010 Abdulla Kamar. All rights reserved. ##

def build( context ):
    platform = context.env.platform

    context.stlib(
        source = 'box_tree.cpp convert_source.cpp font_source.cpp make.cpp null_source.cpp ' +
            'text_layout.cpp tile_source.cpp virtual_texture.cpp',
        system_includes = platform.ui.system_includes,
        target = 'ui' )
