## Copyright (C) 2012 Abdulla Kamar. All rights reserved. ##

def build( context ):
    platform = context.env.platform

    context.stlib(
        source = 'bin.cpp box_tree.cpp convert_source.cpp font_source.cpp make.cpp ' +
            'null_source.cpp text_layout.cpp tile_source.cpp virtual_texture.cpp',
        system_includes = platform.ui.system_includes,
        target = 'ui',
        use = 'math parallel visual' )

    context.program(
        lib = 'tbb',
        source = 'retile/main.cpp',
        target = 'retile/retile',
        use = 'ui' )

    context.program(
        lib = 'tbb',
        source = 'tile/main.cpp',
        target = 'tile/tile',
        use = 'ui' )

    context.program(
        lib = 'tbb',
        source = 'server/main.cpp',
        target = 'server/ui',
        use = 'ui' )

    context.program(
        lib = 'tbb',
        source = 'box_tree_test.cpp virtual_texture_test.cpp',
        target = 'ui_test',
        use = 'ui unit' )
