Import( Split( 'name root' ) )

### build ######################################################################
build = root.Clone()
build.Append( LIBS = Split( 'executable io ipc parallel registry unit' ) )

if name == 'posix':
	build.Append( RPATH = "'$$$${ORIGIN}/../library'" )
elif name == 'darwin':
	build.Append( LINKFLAGS = '-Wl,-rpath,@executable_path/../library' )

out = build.Program( '#binary/registry_test', Glob( '*.cpp' ) )
build.SideEffect( Glob( '*.rpo' ), out )
build.Clean( out, '#binary/registry_test.log' )
