## Copyright (C) 2010 Abdulla Kamar. All rights reserved. ##

def build( context ):
    platform = context.env.platform

    context.program(
        source = 'module_test.cpp registry_test.cpp',
        target = 'registry_test',
        use = 'javascript_link lua_link python_link unit' )
