Import( Split( 'name ooe platform root' ) )
build = root.Clone()
build.Append( LIBS = ooe.pthread.library )

if name == 'darwin':
	build.Append( LINKFLAGS = '-Wl,-install_name,@rpath/libparallel.dylib' )

files = Glob( '*.cpp' ) + Glob( platform + '/foundation/parallel/*.cpp' )
out = build.SharedLibrary( '#library/libparallel', files )
build.SideEffect( Glob( '*.rpo' ), out )
