## Copyright (C) 2012 Abdulla Kamar. All rights reserved. ##

def build( context ):
    platform = context.env.platform

    context.shlib(
        lib = 'tbb',
        linkflags = platform.shlib( 'parallel' ),
        source = 'lock.cpp thread.cpp thread_pool.cpp ' + source( platform.name ),
        target = 'parallel',
        use = 'executable' )

    context.program(
        source = 'thread_pool_test.cpp',
        target = 'parallel_test',
        use = 'parallel unit' )

def source( name ):
    if name == 'darwin':
        return 'darwin/lock.cpp darwin/thread.cpp'
    elif name == 'linux':
        return 'linux/lock.cpp linux/thread.cpp'
