## Copyright (C) 2010 Abdulla Kamar. All rights reserved. ##

def build( context ):
    platform = context.env.platform
    context.shlib(
        includes = platform.image.includes,
        lib = 'Half Iex IlmImf IlmThread jpeg openjpeg png squish z',
        libpath = platform.image.libpath,
        source = 'dds.cpp exr.cpp image.cpp jpeg.cpp jpeg2000.cpp png.cpp',
        target = 'image',
        use = 'io' )
