## Copyright (C) 2012 Abdulla Kamar. All rights reserved. ##

def build( context ):
    platform = context.env.platform

    context.shlib(
        includes = platform.image.includes,
        lib = 'openjpeg png squish turbojpeg z',
        libpath = platform.image.libpath,
        linkflags = platform.shlib( 'image' ),
        source = 'dds.cpp image.cpp jpeg.cpp jpeg2000.cpp png.cpp',
        target = 'image',
        use = 'io' )

    context.program(
        source = 'image_test.cpp',
        target = 'image_test',
        use = 'image unit' )
