/* Copyright (C) 2010 Abdulla Kamar. All rights reserved. */

#ifndef OOE_PLATFORM_DARWIN_FOUNDATION_IPC_SEMAPHORE_FORWARD_HPP
#define OOE_PLATFORM_DARWIN_FOUNDATION_IPC_SEMAPHORE_FORWARD_HPP

#include <semaphore.h>

#endif	// OOE_PLATFORM_DARWIN_FOUNDATION_IPC_SEMAPHORE_FORWARD_HPP
