Import( Split( 'name ooe platform root' ) )

### build ######################################################################
build = root.Clone()

if name == 'darwin':
	build.Append( LINKFLAGS = '-Wl,-install_name,@rpath/libmaths.dylib' )

out = build.SharedLibrary( '#library/libmaths', Glob( '*.cpp' ) )
build.SideEffect( Glob( '*.rpo' ), out )
