Import( Split( 'name root' ) )

### configure ##################################################################
build = root.Clone()

if not build.GetOption( 'clean' ):
	setup = Configure( build )

	build = setup.Finish()

### build ######################################################################
if name == 'darwin':
	build.Append( LINKFLAGS = '-Wl,-install_name,@executable_path/../library/libunit.dylib' )

out = build.SharedLibrary( '#library/libunit', Glob( '*.cpp' ) )
build.SideEffect( Glob( '*.rpo' ), out )
