## Copyright (C) 2010 Abdulla Kamar. All rights reserved. ##

def build( context ):
    context.shlib(
        lib = 'lua',
        source = 'facade.cpp stack.cpp vm.cpp',
        target = 'lua',
        use = 'registry' )
