/* Copyright (C) 2010 Abdulla Kamar. All rights reserved. */

#ifndef OOE_PLATFORM_DARWIN_FOUNDATION_EXECUTABLE_PROGRAM_FORWARD_HPP
#define OOE_PLATFORM_DARWIN_FOUNDATION_EXECUTABLE_PROGRAM_FORWARD_HPP

#define OOE_SIGFAULT SIGBUS

#endif  // OOE_PLATFORM_DARWIN_FOUNDATION_EXECUTABLE_PROGRAM_FORWARD_HPP
